### ISSUE TITLE
All tests fail and library doesn't appear to work

### ISSUE THREAD

**Issue by JL2210** [stewartsmith/libeatmydata#12]
Log file: https://pastebin.com/cte701kz
Libeatmydata doesn't seem to catch data writes and all the tests fail miserably.
I'm using the latest tarball. Any issues with this?

**Comment by JL2210** [comment]
The library still doesn't seem to work, but I see the problem: Strace isn't installed. Let me install it and get back to you.

**Comment by JL2210** [comment]
All the tests now pass. How would I go about testing the library in userspace?

**Comment by JL2210** [comment]
How am I supposed to tell that it works? `fdisk` works, same with `dd`. `nano` can still write files, and `echo` with bash redirection works, also.

**Comment by stewartsmith** [comment]
Sent from my iPhone

> On 2 Nov 2018, at 11:56, James Larrowe <notifications@github.com> wrote:
> 
> How am I supposed to tell that it works? fdisk works, same with dd. nano can still write files, and echo with bash redirection works, also.
> 

Everything should work normally. Only things that are run with the LD_PRELOAD will avoid fsync() though.

What is it you’re trying to achieve?

**Comment by JL2210** [comment]
I'm trying to understand the effects and the usefulness of this. I was hoping to make a package for (Chromebrew)[https://github.com/skycocker/chromebrew].

**Comment by JL2210** [comment]
I'm trying to understand the effects and the usefulness of this. I was hoping to make a package for [Chromebrew](https://github.com/skycocker/chromebrew).

**Comment by stewartsmith** [comment]
On 2 Nov 2018, at 12:16, James Larrowe <notifications@github.com> wrote:
> 
> I'm trying to understand the effects and the usefulness of this. I was hoping to make a package for Chromebrew.
> 

It wraps around other programs and disables any method of crash safety they may have. Specifically, I originally wrote it so that a database server test suite would run quicker.

Ordinary users should *never* use it, if you wrap programs with eat my data and the machine crashes: your data is likely corrupted.
