### ISSUE TITLE
Consider adding INSTALLATION.md

### ISSUE THREAD

**Issue by laurynas-biveinis** [stewartsmith/libeatmydata#26]
Please consider adding INSTALLATION.md with instructions from https://www.flamingspork.com/projects/libeatmydata/

It would help with building from source as remembering the right `autoreconf` call might be non-trivial

**Comment by stewartsmith** [comment]
Not a bad idea, https://github.com/stewartsmith/libeatmydata/commit/2687cd3b15a69e8e9f30ff41552ec666563cba36 does that, just in README, because I'm *really* lazy when it comes to finding build instructions.
